version: "1.0"
services:
  api:
    build: .
    ports:
      - "8080:8080"
    image: px-unittest-stubserver
    container_name: pxUnittestStubserver
    stdin_open: true
    tty: true
  transactionDb:
    image: postgres:12.19
    container_name: transactionDb
    ports:
      - "15432:5432"
    volumes:
      - ./sql/transactionDb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: P@ssw0rd!
      POSTGRES_USER: test
      POSTGRES_DB: transactionDb
    stdin_open: true
    tty: true
  customerDb:
    image: postgres:12.19
    container_name: customerDb
    ports:
      - "15433:5432"
    volumes:
      - ./sql/customerDb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: P@ssw0rd!
      POSTGRES_USER: test
      POSTGRES_DB: customerDb
    stdin_open: true
    tty: true
